version: '2'
services:
  steam-watcher:
    image: node:8.9-alpine
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    command: npm start
    ports:
      - 8080:8080
    environment:
      - IDS=346110
      - SMTP_HOST=smtp-mail.outlook.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=email@outlook.fr
      - SMTP_PASS=pass
      - RECIPIENTS=tahitibob035@gmail.com
